Feature/add form practices
FactoryAdmin/factory-david pull request #1
Opened 2024-09-23 22:40 UTC by DavidQA71

Se agregaron los archivos de práctica de Forms en la carpeta forms-uno

2024-09-24 20:02 UTC, FactoryAdmin requested changes

2024-09-24 20:02 UTC, FactoryAdmin commented on forms-uno/index.html
en los ids de los formularios es redundante poner id-[nombre] porque si lo estamos colocando dentro del atributo id, se entiende que es un id, entonces podemos poner por ejemplo id="userName".

2024-09-24 20:02 UTC, FactoryAdmin commented on forms-uno/register.html
> +    <main class="formContainer">
es raro que dos etiquetas que son diferentes (una es main y la otra div) tengan la misma clase "formContainer" fijate si  podemos hacer una clase global que tenga otro nombre.

2024-09-24 20:02 UTC, FactoryAdmin commented on forms-uno/register.html
> +                    <select name="dni-type" id="dni-id" required>
mismo tema con los ids.

2024-09-24 20:02 UTC, FactoryAdmin commented on forms-uno/web_page.html
misto meta con los ids

2024-09-24 20:02 UTC, FactoryAdmin commented on forms-uno/register.html
Tratar de seguir el diseño planteado en clases en donde cada input tenía su título.

2024-09-25 00:16 UTC, DavidQA71 commented on forms-uno/register.html
> +                    <select name="dni-type" id="dni-id" required>
listo

2024-09-25 00:16 UTC, DavidQA71 commented on forms-uno/web_page.html
listo

2024-09-25 00:16 UTC, DavidQA71 commented on forms-uno/register.html
listo

2024-09-25 00:16 UTC, DavidQA71 commented
all fixed

2024-09-25 22:12 UTC, FactoryAdmin approved these changes

2024-09-25 22:13 UTC, merged